### ISSUE TITLE
"--privileged" is a bit of a hammer

### ISSUE THREAD

**Issue by tianon** [google/android-emulator-container-scripts#16]
Hi!  This project is really cool, thanks for starting it! :metal: :heart:

I was curious about the use of `--privileged` in https://github.com/google/android-emulator-container-scripts/blob/775519de24fb475cc6c31e727cb69f9d5f23e6c7/run.sh#L14 -- is that just to get `/dev/kvm`, or is there more than just KVM support which is necessary?  From a security standpoint, it'd be really interesting if that could be condensed to the minimal set necessary. :sweat_smile:

For example, I run a lot of QEMU containers with `/dev/kvm` using just `--device /dev/kvm`, so I'm guessing there's probably something more clever we could do to make that work without using `--privileged` (which removes a lot of the protections provided by using a container in the first place :smile:).

**Comment by 741g** [comment]
Yep, we use --privileged in order to allow the container to access KVM (Otherwise, the emulator in the container can't be CPU accelerated and will be much slower).

Can you expand on the `--device /dev/kvm` method? If that's a way to run Docker with KVM without `--privileged` that would be awesome. @pokowaka what do you think?

**Comment by tianon** [comment]
Yeah! I've been doing it for quite some time now (https://github.com/tianon/docker-qemu) and it works really well. 😅

The `--device` flag is similar to `-v` but defaults to mounting in the same location and updates the container devices cgroup to allow access to shared device. 👍
