### ISSUE TITLE
How to know when the container is ready?

### ISSUE THREAD

**Issue by BraisGabin** [google/android-emulator-container-scripts#45]
I'm running the images in my CI but I'm having big troubles knowing when the image is ready. I'm using the script [`android-wait-for-emulator`](https://github.com/travis-ci/travis-cookbooks/blob/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator) but when I check with `adb devices` the device is still offline. If I wait for 30 seconds (`sleep 30`) and rerun the `adb devices` it is usually ready.

A script to check if the container is ready to receive commads would be really helpful.

**Comment by plastiv** [comment]
"Ready" is a broad term. There are multiple stages -> device is booted up, os is loaded, system apps are loaded etc. Typically, we want to know when test app can be installed and run. 

I've found that checking for `dev.bootcomplete` system property is a decent approximation. It looks like AndroidStudio is using this property also https://android.googlesource.com/platform/tools/adt/idea/+/studio-master-dev/android/src/com/android/tools/idea/avdmanager/EmulatorConnectionListener.java#146

Having an "official" waiting script would be helpful indeed. Since dev team knows emulator internals better and can avoid guessing.

**Comment by pokowaka** [comment]
Let me see if we can expose this type of status information on the gRPC endpoint. That hopefully will make this a lot easier.

**Comment by pokowaka** [comment]
Once this gets to canary https://android-review.googlesource.com/c/platform/external/qemu/+/116286 we will be able to check if the emulator has booted.

**Comment by pokowaka** [comment]
The docker containers now include a health check that is using ADB to check if the device is in a boot complete state. 

The device should be ready if the container is reporting a healthy status. Let me know if this would suit your needs

**Comment by pokowaka** [comment]
Feel free to reopen if this is not working as expected.
